// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANjCry_J2o6mkAritvnyJ8lEf30l58_V0',
    appId: '1:88013242424:web:8a3eea28e72e11e7da66cd',
    messagingSenderId: '88013242424',
    projectId: 'university-event-9ae4e',
    authDomain: 'university-event-9ae4e.firebaseapp.com',
    storageBucket: 'university-event-9ae4e.appspot.com',
    measurementId: 'G-Y3QL1HEPXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3xs1YdDfxgJ1unz2bfK4d1nkbKfbbXWw',
    appId: '1:88013242424:android:7a5ff49c1e4617c9da66cd',
    messagingSenderId: '88013242424',
    projectId: 'university-event-9ae4e',
    storageBucket: 'university-event-9ae4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAliy1XHWNeYYevMsiepAtqL6jLPB7BGA',
    appId: '1:88013242424:ios:b8290b4dedb3d2bbda66cd',
    messagingSenderId: '88013242424',
    projectId: 'university-event-9ae4e',
    storageBucket: 'university-event-9ae4e.appspot.com',
    iosBundleId: 'com.rsc.eventNode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAliy1XHWNeYYevMsiepAtqL6jLPB7BGA',
    appId: '1:88013242424:ios:b8290b4dedb3d2bbda66cd',
    messagingSenderId: '88013242424',
    projectId: 'university-event-9ae4e',
    storageBucket: 'university-event-9ae4e.appspot.com',
    iosBundleId: 'com.rsc.eventNode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANjCry_J2o6mkAritvnyJ8lEf30l58_V0',
    appId: '1:88013242424:web:7a705c67c55a234dda66cd',
    messagingSenderId: '88013242424',
    projectId: 'university-event-9ae4e',
    authDomain: 'university-event-9ae4e.firebaseapp.com',
    storageBucket: 'university-event-9ae4e.appspot.com',
    measurementId: 'G-K4NM78E94W',
  );
}
